main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
author: dev.beerops
description: DESCRIPTION
commands:
  ex:
    description: Base command for EXAMPLE
    usage: "For a list of commands, type /ex help"
    aliases: example
permissions:
  ee.test:
    description: DESCRIPTION
    default: true
  ee.*:
    description: Grants all other permissions
    default: false
    children:
      ee.test: true